name: Publish packages to Nuget

inputs:
  token:
    description: |
      GitHub personal access token that this action should use. This should be configured using a Secret.
    required: true
  owner:
    description: |
      The owner of the GitHub Packages where to push.
    required: true

runs:
  using: composite
  steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0

    - name: Download packages artifacts
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        pattern: packages-*
        path: packages
        merge-multiple: true

    - name: Push to GitHub
      shell: sh
      run: dotnet nuget push packages/Microsoft.*.freebsd-*.*.nupkg --no-symbols --skip-duplicate --source https://nuget.pkg.github.com/${{ inputs.owner }}/index.json --api-key ${{ inputs.token }}
