name: Publish packages to Nuget

inputs:
  token:
    description: |
      GitHub personal access token that this action should use. This should be configured using a Secret.
    required: true
  owner:
    description: |
      The owner of the GitHub Packages where to push.
    required: true

runs:
  using: composite
  steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0

    - name: Download packages artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        pattern: packages-*
        path: packages
        merge-multiple: true

    - name: Push to GitHub
      shell: sh
      run: dotnet nuget push packages/Microsoft.*.freebsd-*.*.nupkg --no-symbols --skip-duplicate --source https://nuget.pkg.github.com/${{ inputs.owner }}/index.json --api-key ${{ inputs.token }}
